### ISSUE TITLE
Snort dashboard

### ISSUE THREAD

**Issue by jarmouz** [markwalkom/kibana-dashboards#7]
Hello,

I thank you for the work you have done.
After installing the snort dashboard, how can I retrieve data from MySQL snort database to see on the dashboard?

thank you

**Comment by markwalkom** [comment]
You need to extract it from there somehow, it's out of scope for this repository sorry.

The only thing I can do is point you to https://github.com/markwalkom/kibana-dashboards/blob/logstash-confs/configurations/James21339540-snort.conf

**Comment by jarmouz** [comment]
Thank you.
But i use unified log with barnyard2.
this is an example : 
03/15-03:36:43.019211  [**] [1:10000001:1] Snort Alert [1:10000001:1] [**] [Classification ID: 0] [Priority ID: 0] {ICMP} 192.168.1.1 -> 192.168.1.100
03/15-03:36:44.077228  [**] [1:10000001:1] Snort Alert [1:10000001:1] [**] [Classification ID: 0] [Priority ID: 0] {ICMP} 192.168.1.100 -> 192.168.1.1
03/15-03:36:44.078546  [**] [1:10000001:1] Snort Alert [1:10000001:1] [**] [Classification ID: 0] [Priority ID: 0] {ICMP} 192.168.1.1 -> 192.168.1.100
how can i make my conf file with filter?
